---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170701090350"
editor:
  name: "AddFeatureFollowerEditor"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.7.3"
  origin:
    repo: "git@github.com:atomisthq/spring-team-handlers.git"
    branch: "a2dcd580283cd28d8a72acc1cb4b4e4516b959de"
    sha: "a2dcd58"
  parameters:
    - "broadcaster": "java-lib-seed"
    - "follower": "tanyatest11"
    - "featureName": "SpringBoot.Structure"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170728065612"
editor:
  name: "AddFeatureFollowerEditor"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.7.9"
  origin:
    repo: "git@github.com:atomisthq/spring-team-handlers.git"
    branch: "4048638c0f9941d771fbd8436204148b144ff3e5"
    sha: "4048638"
  parameters:
    - "broadcaster": "java-lib-seed"
    - "follower": "Toto"
    - "featureName": "SpringBoot.Structure"

